version: '3'
services:
  c1:
    build: base/netopeer-cli
    hostname: c1
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    networks:
        c2c:
            ipv4_address: 172.24.4.100
        sdn_control:
            ipv4_address: 10.0.1.200
  c2:
    build: base/netopeer-cli
    hostname: c2
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    networks:
        c2c:
            ipv4_address: 172.24.4.200
        sdn_control2:
            ipv4_address: 10.0.2.200
  gw1:
    build: base/netopeer-server
    hostname: gw1
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    environment:
      - NETCONF_USER=netconf
      - NETCONF_PASSWORD=netconf
      - SDN_NET=10.0.1.0/24
    depends_on:
      - "c1"
    networks:
        sdn_control:
            ipv4_address: 10.0.1.204
        gw1_gw2_data:
            ipv4_address: 192.168.123.100 
        gw1_data:
            ipv4_address: 192.168.201.2 
  h1:
    build: base/netopeer-cli
    hostname: h1
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    environment:
      - NETCONF_USER=netconf
      - NETCONF_PASSWORD=netconf
      - SDN_NET=10.0.1.0/24
    depends_on:
      - "c1"
    networks:
        sdn_control:
            ipv4_address: 10.0.1.102
        gw1_data:
            ipv4_address: 192.168.201.254
  gw2:
    hostname: gw2
    build: base/netopeer-server
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    environment:
      - NETCONF_USER=netconf
      - NETCONF_PASSWORD=netconf
      - SDN_NET=10.0.2.0/24
    depends_on:
      - "c2"
    networks:
        sdn_control2:
            ipv4_address: 10.0.2.234
        gw1_gw2_data:
            ipv4_address: 192.168.123.200 
        gw2_data:
            ipv4_address: 192.168.202.2
  h2:
    hostname: h2
    build: base/netopeer-cli
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    environment:
      - NETCONF_USER=netconf
      - NETCONF_PASSWORD=netconf
      - SDN_NET=10.0.2.0/24
    depends_on:
      - "c2"
    networks:
        sdn_control2:
            ipv4_address: 10.0.2.18
        gw2_data:
            ipv4_address: 192.168.202.254
networks:
  sdn_control:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.1.0/24
    driver_opts:
     com.docker.network.bridge.name: sdn_control
  sdn_control2:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.2.0/24
    driver_opts:
     com.docker.network.bridge.name: sdn_control2
  gw1_gw2_data:
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.123.0/24
    driver_opts:
     com.docker.network.bridge.name: gw1_gw2_data
  gw1_data:
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.201.0/24
    driver_opts:
     com.docker.network.bridge.name: gw1_data   
  gw2_data:
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.202.0/24
    driver_opts:
     com.docker.network.bridge.name: gw2_data   
  c2c:
    driver: bridge
    ipam:
     config:
       - subnet: 172.24.4.0/24
    driver_opts:
     com.docker.network.bridge.name: c2c